# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('age', models.CharField(blank=True, max_length=5)),
                ('image', models.ImageField(default=b'/static/img/egg.jpg', upload_to=b'static/img/')),
                ('spotify', models.CharField(blank=True, max_length=430)),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one2one_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='posters',
            name='following',
        ),
        migrations.RemoveField(
            model_name='posters',
            name='username',
        ),
        migrations.DeleteModel(
            name='Posters',
        ),
    ]
