# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20170330_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mess',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='mess',
            name='reality_coefficient',
            field=models.BooleanField(default=True),
        ),
    ]
