# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_searchres'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=160)),
                ('uri', models.CharField(max_length=160)),
                ('img', models.CharField(max_length=160)),
                ('popularity', models.CharField(max_length=160)),
                ('created', models.DateTimeField(default=None)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
