# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_artistres'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchres',
            name='popularity',
            field=models.CharField(default=69, max_length=160),
            preserve_default=False,
        ),
    ]
