# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_searchres_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchres',
            name='img',
            field=models.CharField(default='../../static/img/egg.png', max_length=160),
            preserve_default=False,
        ),
    ]
