# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20170418_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=160)),
                ('created', models.DateTimeField(default=None)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
