# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_genreres'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.CharField(max_length=160)),
                ('created', models.DateTimeField(default=None)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
