# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_playlistres'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistres',
            name='followers',
            field=models.CharField(default=b'', max_length=160),
        ),
        migrations.AddField(
            model_name='playlistres',
            name='img',
            field=models.CharField(default=b'', max_length=160),
        ),
        migrations.AddField(
            model_name='playlistres',
            name='owner',
            field=models.CharField(default=b'', max_length=160),
        ),
        migrations.AddField(
            model_name='playlistres',
            name='trackcount',
            field=models.CharField(default=b'', max_length=160),
        ),
        migrations.AddField(
            model_name='playlistres',
            name='uri',
            field=models.CharField(default=b'', max_length=160),
        ),
        migrations.AlterField(
            model_name='playlistres',
            name='playlist',
            field=models.CharField(default=b'', max_length=160),
        ),
    ]
