# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_auto_20170419_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistres',
            name='ownerid',
            field=models.CharField(default=b'', max_length=160),
        ),
    ]
