# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_auto_20170421_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='ordering',
            new_name='index',
        ),
        migrations.AddField(
            model_name='tracks',
            name='index',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
