# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_auto_20170421_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatters',
            name='top_artists',
        ),
        migrations.RemoveField(
            model_name='chatters',
            name='top_tracks',
        ),
        migrations.AddField(
            model_name='artists',
            name='top_artists',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topartists', to='chatbot.Chatters'),
        ),
        migrations.AddField(
            model_name='tracks',
            name='top_tracks',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toptracks', to='chatbot.Chatters'),
        ),
    ]
