# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_auto_20170421_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=160)),
                ('created', models.DateTimeField(default=None)),
                ('number', models.CharField(max_length=10)),
                ('top_genres', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_genres', to='chatbot.Chatters')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
