# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='top_genres',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topgenres', to='chatbot.Chatters'),
        ),
    ]
