# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_auto_20170422_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='acousticness',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='danceability',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='instrumentalness',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='key',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='liveness',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='loudness',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='speechiness',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='time_signature',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='valence',
        ),
        migrations.AddField(
            model_name='tracks',
            name='acousticness',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='danceability',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='energy',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='instrumentalness',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='key',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='liveness',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='loudness',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='speechiness',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='tempo',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='time_signature',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='valence',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=7, null=True),
        ),
    ]
