# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_auto_20170422_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='acousticness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='danceability',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='energy',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='instrumentalness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='key',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='liveness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='loudness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='speechiness',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='tempo',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='time_signature',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='valence',
            field=models.FloatField(default=None, null=True),
        ),
    ]
