# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0030_hottracks_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatters',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='chatters',
            name='email',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='chatters',
            name='lname',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
