# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0031_auto_20170424_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatters',
            name='name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
