# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0033_auto_20170424_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='context',
            field=models.TextField(default=None, null=True),
        ),
    ]
