# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0034_mess_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistres',
            name='img',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artists',
            name='img',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hottracks',
            name='img',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='playlistres',
            name='img',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AlterField(
            model_name='searchres',
            name='img',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='img',
            field=models.CharField(max_length=300),
        ),
    ]
